### ISSUE TITLE
Computing ground truth SMPL parameters for Human3.6M

### ISSUE THREAD

**Issue by paulgrassler** [meysam-madadi/SMPLR#1]
Hey, this is more a question regarding the paper than an issue with the repo. I hope it is not a bother that I chose to use github for this purpose. So in your paper in the section about the datasets (4.2) you mention that you "generated ground truth SMPL parameters from the 3D data and body scans available in the dataset" (concerning Human3.6m). I am currently writing a thesis about 3d human reconstruction and a way to generate these SMPL parameters for H36M would be really convenient at the stage I am at. Since I am not the most knowledgeable in this area, I am not quite sure how you generated these ground truth parameters given the dataset. Could you maybe help me out here?
Thank you in advance!

**Comment by meysam-madadi** [comment]
Hi. We did it in two stages. For the shape parameters we used the scans in which the pose is fixed and then optimized shape parameters using chamfer distance to match the ground truth point cloud. After fixing the shape parameters we optimized the pose parameters per frame using 3D ground truth joint locations. This is a little trickier because the SMPL joints locations do not match with the human3.6m. This can cause monsters with unrealistic twisted joints. Therefore we used several constraints/regularizations on the joints orientations. Also we discarded some joints in the optimization.

You can check SMPLify or unite the people papers (and similar papers) for more information.
